import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../../components/Sidebar";
import TopBar from "../../components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[var(--background)] text-[var(--foreground)] antialiased`}
      >
        <div className="flex min-h-screen">
          <div className="z-30">
            <Sidebar />
          </div>
          <div className="relative ml-20 flex min-h-screen flex-1 flex-col">
            <TopBar />
            <main className="flex-1 px-5 py-4 lg:px-6 lg:py-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
